backend:
  name: github
  repo: LotharVM/gatsby-blog

media_folder: static/assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }